In [23]:
#1 . Tạo dataframe
import pandas as df

 = pd.DataFrame({"Họ và tên": ["An", "Bình", "Cường", "Dung", "Bảo", "Hương", "Khoa", "Lan", "Minh", "Ngọc"], "Chuyên cần": [9,8,10,7,9,8,10,9,7,8],"Giữa kỳ": [8,7,9,6,8,7,9,8,6,7],"Cuối kỳ": [9,8,10,7,9,8,9,9,7,8]})
display(df)

  Họ và tên  Chuyên cần  Giữa kỳ  Cuối kỳ  Tong_ket
0        An           9        8        9       8.7
1      Bình           8        7        8       7.7
2     Cường          10        9       10       9.7
3      Dung           7        6        7       6.7
4       Bảo           9        8        9       8.7
5     Hương           8        7        8       7.7
6      Khoa          10        9        9       9.2
7       Lan           9        8        9       8.7
8      Minh           7        6        7       6.7
9      Ngọc           8        7        8       7.7

In [22]:
#2. Tính điểm tổng kết
df["Tong_ket"] = df["Chuyên cần"]*0.2 + df["Giữa kỳ"]*0.3 + df["Cuối kỳ"]*0.5

display(df)

  Họ và tên  Chuyên cần  Giữa kỳ  Cuối kỳ  Tong_ket
0        An           9        8        9       8.7
1      Bình           8        7        8       7.7
2     Cường          10        9       10       9.7
3      Dung           7        6        7       6.7
4       Bảo           9        8        9       8.7
5     Hương           8        7        8       7.7
6      Khoa          10        9        9       9.2
7       Lan           9        8        9       8.7
8      Minh           7        6        7       6.7
9      Ngọc           8        7        8       7.7

In [35]:
#3 .Xếp loại sinh viên
def xep_loai(diem):
    if diem >= 8.5:
       return("giỏi")
    elif 7<= diem <8.5:
       return("khá")
    elif 5<= diem <7:
       return("trung bình")
    else :
      return("yếu")

df["Xep_loai"] = df["Tong_ket"].apply(xep_loai)
display(df)

  Họ và tên  Chuyên cần  Giữa kỳ  Cuối kỳ  Tong_ket    Xep_loai
0        An           9        8        9       8.7        giỏi
1      Bình           8        7        8       7.7         khá
2     Cường          10        9       10       9.7        giỏi
3      Dung           7        6        7       6.7  trung bình
4       Bảo           9        8        9       8.7        giỏi
5     Hương           8        7        8       7.7         khá
6      Khoa          10        9        9       9.2        giỏi
7       Lan           9        8        9       8.7        giỏi
8      Minh           7        6        7       6.7  trung bình
9      Ngọc           8        7        8       7.7         khá

In [38]:
#4. Thống kê
print("Điểm trung bình:", df["Tong_ket"].mean())
print(df.loc[df["Tong_ket"].idxmax()])
print(df.loc[df["Tong_ket"].idxmin()])
print("Số sinh viên đạt:", (df["Tong_ket"] >= 5).sum())

Điểm trung bình: 8.15
Họ và tên     Cường
Chuyên cần       10
Giữa kỳ           9
Cuối kỳ          10
Tong_ket        9.7
Xep_loai       giỏi
Name: 2, dtype: object
Họ và tên           Dung
Chuyên cần             7
Giữa kỳ                6
Cuối kỳ                7
Tong_ket             6.7
Xep_loai      trung bình
Name: 3, dtype: object
Số sinh viên đạt: 10